# Generated by Django 3.0.6 on 2020-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
